# This is a basic workflow to help you get started with Actions

name: Build Source

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the will run on
    runs-on: ubuntu-latest
    container: ghcr.io/ozipoetra/docker:main

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell

      - name: Build
        run: |
          cd ~
          mkdir clang
          wget -q https://github.com/mitsu00/build_test/releases/download/clang/clang.zip
          unzip -q clang.zip -d clang
          export PATH="$(pwd)/clang/bin:$PATH"
          wget -q https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip
          unzip -q android-ndk-r10e-linux-x86_64.zip
          export ANDROID_NDK_HOME="~/android-ndk-r10e"
          export NDK_HOME="~/android-ndk-r10e"
          git clone https://github.com/nillerusr/source-engine --recursive --depth=1
          cd source-engine
          ./waf configure -T release --android=aarch64,host,21 --togles --disable-warns --64bits
          ./waf build
          echo "Build Log"
          cat build/config.log
